### ISSUE TITLE
MembraneConfiguration is not an auto-configuration and yet uses conditions

### ISSUE THREAD

**Issue by snicoll** [helpermethod/membrane-spring-boot-starter#8]
This starter is not really providing an auto-configuration but rather a regular `Configuration` that is enabled via `@EnableMembrane`

According [to its Javadoc](http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnMissingBean.html), we strongly discourage you from using `@ConditionalOnMissingBean` and friend on regular configuration classes.

Besides, since this isn't an auto-configuration, it doesn't show up in the auto-configuration report.

**Comment by helpermethod** [comment]
Hi,

thank you for reviewing the project.

In the beginning I actually had a `spring.factories` file defined but following the example of `spring-cloud-starter-zuul` I've decided to only configure the Membrane Proxy when the annotation is set.

Can I provide an autoconfiguration and still require the annotation to be set?

**Comment by snicoll** [comment]
It is an excellent question and I've been wondering that myself recently actually. There is the option of creating a basic bean and then have the auto-configuration react on the presence of said bean. This may or may not work for you.  If that doesn't, let me know and I'll dig a bit more.

**Comment by helpermethod** [comment]
Hi,

I managed to conditionally load the `MembraneAutoConfigurationBean` by implementing a custom `AutoConfigurationImportSelector`

```java
public class MembraneAutoConfigurationImportSelector extends AutoConfigurationImportSelector {
    @Override
    public String[] selectImports(AnnotationMetadata annotationMetadata) {
        return new String[] { "com.github.helpermethod.membrane.starter.MembraneAutoConfiguration" };
    }
}
```

which is then imported via the `@EnableMembrane` annotation

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Import(MembraneAutoConfigurationImportSelector.class)
public @interface EnableMembrane {
}
```
This was the cleanest solution I could come up with.

**Comment by snicoll** [comment]
@helpermethod that is wrong. If you import an auto-configuration that way it is no longer an auto-configuration (the lifecycle is wrong) and you are basically doing the exact same thing as before. Your "auto-configuration" is loaded as part of the user's configuration round.

If you have a bean that signals that you want to use that stuff, perhaps the import thing should create it and then your auto-configuration should react to the presence of said bean.

**Comment by helpermethod** [comment]
Thank you,

I've now applied your suggestion and implemented a `marker` bean whose presence I can query in the AutoConfiguration

```java
@Configuration
public class MembraneMarkerConfiguration {
    @Bean
    public Marker membraneMarkerBean() {
        return new Marker();
    }

    class Marker {
    }
}
```
Works like a charm!

**Comment by snicoll** [comment]
I haven't a marker bean in mind though but something basic that makes sense for the thing you want to auto-configure. If that works for you, that's fine by me. Maybe we can close this one then?
